rhbase_install_packages:
  - bind-utils
  - bash-completion
  - git
  - nano
  - vim-enhanced
  - tree
  - wget
  - samba-client

nginx_vhosts:
  - listen: "443 ssl http2"
    server_name: 192.168.55.4
    root: "/var/www/html/drupal"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "drupal.conf"
    extra_parameters: |
      access_log /var/log/nginx/drupal.access.log;
      error_log /var/log/nginx/drupal.error.log;
      ssl_certificate     /vagrant/ansible/files/charlie.crt;
      ssl_certificate_key /vagrant/ansible/files/charlie.key;
      ssl_dhparam         /vagrant/ansible/files/dhparam.pem;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
      ssl_ecdh_curve secp384r1;
      ssl_session_cache shared:SSL:10m;
      ssl_session_tickets off;
      ssl_stapling on;
      ssl_stapling_verify on;
      resolver 8.8.8.8 8.8.4.4 valid=300s;
      resolver_timeout 5s;
      add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;
      location / {

      }
      location @rewrite {
      rewrite ^/(.*)$ /index.php?q=$1;
      }

      location ~ .php$ {
      include fastcgi_params;
      fastcgi_intercept_errors on;
      fastcgi_pass unix:/var/run/php-fpm/www.sock;
      fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
      }

      location ~ ^(/[a-z-]+)?/system/files/ {
      try_files $uri /index.php?$query_string;
      }
      error_page 404 /404.html;
      location = /404.html {
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
      }
  - listen: "80"
    server_name: "ssl-redirect"
    return: "301 https://$host$request_uri"
    filename: "drupal.80.conf"